title: Multiple Failed Logon Attempts
id: 0e95725d-7320-415d-80f7-004da920fc11
status: stable
level: high
description: Detects multiple failed logon attempts indicating brute force.
author: Guardian SIEM
date: 2025/01/01
tags:
- attack.credential_access
- attack.t1110
logsource:
  product: windows
  service: security
detection:
  selection:
    EventID:
    - 4625
  condition: selection
falsepositives:
- Misconfigured service accounts
